version: "3.8"

services:
  # Serviciul pentru API REST
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydb
      - FLASK_ENV=development
    volumes:
      - ./api:/app
    depends_on:
      - db

  # Serviciul pentru PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Serviciul pentru pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com # Adresa de email pentru autentificare
      - PGADMIN_DEFAULT_PASSWORD=adminpassword # Parola pentru autentificare
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
